[package]
name = "diffie-hellman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-zk-token-sdk = "1.14.5"
curve25519-dalek = "^3.2.1"
solana-sdk = "1.14.5"
zeroize = "^1.3.0"
rand = "^0.7"